### ISSUE TITLE
Small Feedback

### ISSUE THREAD

**Issue by doublemarked** [kevinfaguiar/cool-emoji-picker#10]
Hello! I quite like your component, and we're currently incorporating it into our project. I want to share with you a couple pieces of feedback we encountered when integrating it,

1. `outerDivClasses`: This appears like an anti-pattern, redundant with built-in Vue functionality. Generally the best approach for applying a class to a component you're using is to just use `class="..."` or ":class="[...]"`, which Vue will automatically apply to the element of the component.

2. `innerDivClasses`: A bit more convenient, but probably better to adjust style with a child selector, `.my-emoji-textarea >>> .cooltextarea { ... } `

3. We don't want to swallow enter keys, and are currently calling your `shiftEnterKey` from an `enterKey` handler. It would be great if your `enterKey` event would pass the event handle up, so that we can pass it on to your `shiftEnterKey` method, rather than making a fake Event.

4. Speaking of the `enterKey` event - why not just propagate the `keyup.enter`, just like you caught? You can still stifle it for swallowing enter keys when they should be swallowed, but so long as you're emitting an enter key event, it might as well be the actual native event, or at least the standard naming convenient...

5. Fewer `!important`s in the CSS would make it easier to override styling.

6.  `componentColor` should accept something like `null` or `transparent` 

7. In your sample code there's a small typo at `components: { 'cooltextarea': CoolTextarea }`: The 'a' should be capitalized: `CoolTextArea`

**Comment by kevinfaguiar** [comment]
Hey there! 
How cool to know you are using my component into a commercial app!
As for the feedback:
1 and 2: Really valid points... Will probably refac this for the next release.
3 and 4: Sounds like an interesting refactoring. I will think a little more about this one.
5: Is in my plans a major refactor of the styling, which will focus too on being more clean.
6: I think a 'transparent' option for the prop componentColor is a good thing.
7: Hmm... Will look into fixing this docs (also, I'm planning a complete rewrite of the docs using VuePress until the end of the current year).

I really appreciate the feedback, I believe it was very constructive. I will mark this Issue as an improvement, and when I develop an answer to all the points listed I will write here.

**Comment by doublemarked** [comment]
All sounds good! :) Thanks for your reply!

**Comment by kevinfaguiar** [comment]
@doublemarked I've made a major rework on the library bundling, so it now has ESM, commons and UMD bundles. I've also updated a lot of dependencies, so if something breaks, don't hesitate in opening an issue here :smile: 

I've also addressed some points made by you (starting with version 4.0.3 of this lib):

1 and 2: The classes props, two for CoolTextArea and one for CoolPicker have been deleted because I found the library to became way cleaner removing these props... So now you need to write your style and overwrite the default.

3 and 4: I think that propagate the enter keypress event as I caught is the best solution for this. Now the @enterKey just propagates the event (it do not preventDefault and stopPropagation anymore) to the parent through the Vue $emit.

5: I have made a refactor into the styles, so '!important' declarations are almost nonexistent and should be way easier to overwrite styles.

6: A transparent option for the entire CoolTextArea component has been added.

7: I've fixed some typos at the docs but I still plan to rewrite all docs using VuePress.

PS: If you are using cool-emoji-picker in a version below 4.0.0 the path for the emoji-data is 'cool-emoji-picker/src/emoji-data'. Otherwise, if on 4.0.0+ it will be 'cool-emoji-picker/emoji-data'.
